# Generated by Django 5.2.4 on 2025-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fooditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='variant',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('restaurant_admin', 'Restaurant Admin'), ('customer', 'Customer')], max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together={('restaurant', 'name', 'variant')},
        ),
    ]
