# Generated by Django 5.2.4 on 2025-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ingredients_diseases_fooditem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='description',
        ),
    ]
