# Generated by Django 5.2.4 on 2025-07-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_diseaserequest_ingredientrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseaserequest',
            old_name='requested_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredientrequest',
            old_name='requested_by',
            new_name='user',
        ),
    ]
