# Generated by Django 5.2.4 on 2025-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_requested_by_diseaserequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('alreadyexists', 'AlreadyExists')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('alreadyexists', 'AlreadyExists')], default='pending', max_length=20),
        ),
    ]
