# Generated by Django 5.2.4 on 2025-07-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='diseaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('already_exists', 'Already Exists')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('already_exists', 'Already Exists')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='diseases',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_disease_name_case_insensitive'),
        ),
        migrations.AddField(
            model_name='customer',
            name='diseases',
            field=models.ManyToManyField(blank=True, null=True, to='api.diseases'),
        ),
        migrations.AddField(
            model_name='customer',
            name='restricted_ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='api.ingredients'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
