# Generated by Django 5.2.4 on 2025-07-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer_alter_diseaserequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allowed_ingredients',
            field=models.ManyToManyField(blank=True, related_name='allowed_ingredients', to='api.ingredients'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='api.diseases'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restricted_ingredients',
            field=models.ManyToManyField(blank=True, related_name='restricted_ingredients', to='api.ingredients'),
        ),
    ]
